### ISSUE TITLE
UTF-8 – CP1252 encoding issue in exported HTML report

### ISSUE THREAD

**Issue by inigohidalgo** [datapane/datapane#142]
### System Information

- OS: Windows 10
- Python version: 3.8.10
- Python environment: conda
- Using jupyter: true
- Datapane version: 0.11.11

### Bug / Issue

When displaying a pandas dataframe in DataPane as a Table (not DataTable, which does work correctly), euro sign characters (€) display as â¬:

![image](https://user-images.githubusercontent.com/20395965/128697082-a1808d55-a01a-4a0a-9653-381284db7f7b.png)

This doesn't happen inside JupyterLab, or when exporting the original dataframe to html using `df.to_html()`. I am calling `report.save()` rather than `upload` as I want to generate local html reports.

In #9 you mention it could be an issue with Windows' default encoding not being UTF-8, are there any steps I should take to fix this?

Thank you!

**Comment by mands** [comment]
Hi @inigohidalgo 

Thanks for raising - sorry about that, we should have a fix out within the next few days!

**Comment by mands** [comment]
Hi @inigohidalgo,

Haven't tracked down the root cause yet - but thank you so much for that additional information, that really helps!

Think you are correct that it's an locale / encoding issue somewhere - however not sure exactly where in the stack it's occurring. Seems to be an issue particularly on Windows installs with non-English default locales (see https://github.com/datapane/datapane/discussions/140 also) - so I think we may be making some invalid default assumptions around encodings.

Have yet to dig into fully, so any further thoughts you have would be valuable - but will dedicate a few days this week to fixing.

**Comment by inigohidalgo** [comment]
Some further info. In #115 I saw OP was having this issue with text too whereas text worked fine for me, but he was importing a md file while I was sending the text through directly from Python as strings. Turns out I have the same issue. The following code leads to the output I attach below.

![image](https://user-images.githubusercontent.com/20395965/129002893-282571c8-7542-4a61-b44a-f9bc9d0c434e.png)

![image](https://user-images.githubusercontent.com/20395965/129002741-73f106ad-56e5-4ed5-9d71-8a269caa892f.png)

The only text correctly displayed is the one where I manually specified the UTF-8 encoding. This is because, from what I gather, python uses `locale.getpreferredencoding()` to decode by default, which on my machine is cp1252.

The html tables being generated when saving as temp files are UTF-8 encoded, and the code is then reading the bytes in the line I referenced in [this comment](https://github.com/datapane/datapane/issues/142#issuecomment-896108663).

The way the characters are displaying seems to 100% be due to decoding UTF-8 encoded text using the cp1252 character map, since when I read the bytes myself and decode using cp1252 this is what happens, note the last line:
![image](https://user-images.githubusercontent.com/20395965/129002445-f552a000-b117-453d-8161-850d19dd8d58.png)

Which as you can see is the same as the wrongly displayed text in the generated report.

![image](https://user-images.githubusercontent.com/20395965/129004362-869be8f9-a02c-4077-ba9c-011af54acd1c.png)


The objects are being passed through in the HTML and this is where I get lost and can't be of any further help, but my suggestion would be to check the default encoding assumed by JavaScript, or whatever part of your stack is reading the `_E` element being sent through. From what I see in the HTML template the charset is defined as UTF-8, but I don't know if this applies when reading the b64 encoded binaries.

**Comment by mands** [comment]
@inigohidalgo thanks for the detailed investigation - that really helped!

There were 2 different issues here,
1. We were not handling utf-8 encoding correctly in the browser, as per your investigation, resulting in the encoding issues you were seeing with `dp.Table`
2. The issue with `dp.File` actually turned out to be a Windows / Python compatibility issue - where Python defaults to using the locale encoding when reading files if one is not specified. This is usually ok, but many tools on Windows now crate utf-8 files by default, including Notepad, so you can have a case where the file is utf-8, but python is reading it using `windows-1252` encoding - resulting in the issue both here and in #115. We've fixed that now by attempting to autodetect utf-8 files on Windows and decode accordingly. (There is actually a PEP to change the default read behaviour - see https://discuss.python.org/t/pep-597-use-utf-8-for-default-text-file-encoding/1819)

We've just released a fix to both of these that will be pushed to pip in a few days.

Thanks again!
