### ISSUE TITLE
Support geopandas tables

### ISSUE THREAD

**Issue by robmarkcole** [datapane/datapane#161]
### Bug / Issue
Possibly a bug, or a known limitation. I am working with [geodataframes](https://geopandas.org/index.html) and wish to upload these as browsable tables. However on attempt I get errors:

```python
table = dp.DataTable(gdf) # gdf is geopandas.geodataframe.GeoDataFrame
report = dp.Report(table)
report.upload(name='gis_table') 
.
.
.
ArrowTypeError: ('Did not pass numpy.dtype object', 'Conversion failed for column geometry with type geometry')
```

**Comment by fgenoese** [comment]
Probably related to pyarrow, see here:

https://github.com/streamlit/streamlit/issues/1002#issuecomment-939123060

**Comment by mands** [comment]
Yep, this is related `pyarrow`, which is the underlying format we use to store dataframes. A workaround may be to use `dp.Table` instead of `dp.DataTable`, but unfortunately this won't be interactive.

We'll look at what we can do to improve support for `geodataframes` going forwards and update the docs accordingly.
