### ISSUE TITLE
Published data from earth engine in colab to data pane permanently not temporary? 

### ISSUE THREAD

**Issue by StephHerb** [datapane/datapane#191]
I published data that I mapped using geemap.Map in Colab but now when I (or others), try to open the map on datapane, there is no data showing and it only shows the basemap.  Is there a way to make the sharing of the data permanent and not temporary?

**Comment by lanthias** [comment]
I may be wrong, but I believe the problem here lies with the expiry of a token which Folium uses when interactively with Google Maps. One solution would be to schedule your map to be recreated on a cadence so you get a fresh token.

AFAIK this is not a Datapane-specific problem, so you might get a more helpful answer on https://github.com/giswqs/geemap/issues

**Comment by shahinrostami** [comment]
Hi @StephHerb! Are you still encountering this issue following @lanthias's suggestion?

**Comment by shahinrostami** [comment]
Closing this issue in the meantime, please re-open it if you're still encountering it!
