### ISSUE TITLE
Print only seems to render portion of screen for printing rather than whole document

### ISSUE THREAD

**Issue by dahanoo** [datapane/datapane#22]
**Describe the bug**

When trying to print out the demo's, print only seems to render the portion of the screen for printing rather than the whole document.

Reason for trying this: My aim was to see whether a report can be printed to PDF.

**To Reproduce**
From browser choose print, then preview or print.

**Expected behavior**
The whole document should be printed.

- OS: Windows 10
- Browser: Chrome
- Version 84.0.4147.125

**Comment by lanthias** [comment]
Thank for the issue! I can repro this.

This is because we're adding overflow CSS and `height: 100%` to the main HTML element, which we can remove to allow this in the next release.

In the longer term, we are considering adding renderers for both PDF and email, so you can do this a bit more elegantly. Any suggestions about how you would like this to work with more interactive elements would be much appreciated.

Thanks!

**Comment by Kyxsune** [comment]
Was this fixed or is there intention to fix this? I still get the single page render result when I attempt to print it ^^;

**Comment by M-I-Dx** [comment]
Any update on this? I too am still getting single-page render results.
