### ISSUE TITLE
Bloated html.

### ISSUE THREAD

**Issue by dahanoo** [datapane/datapane#24]
**Describe the bug**
An observation more than a bug. 

I ran a simple demo report which generated a 'test' HTML file which weighed in at nearly 10mb. However, when I downloaded the data to csv it was just 191kb. 

I personally would use anywhere from 10 to 50,000 rows for a generalized report. I'm sure there would be cases for larger sizes too.

Run this demo file, download the csv from the generated report then check the size of the csv

```
import pandas as pd
import datapane as dp

df = pd.DataFrame({
    'A': np.random.normal(-1, 1, 5000),
    'B': np.random.normal(1, 2, 5000),
})

table = dp.Table(df)
report = dp.Report(table)
report.save(path='test.html')
```

**Comment by Buroni** [comment]
Hi @dahanoo thanks for bringing this up. Our local HTML report files are large because we include all the NPM packages necessary to generate any kind of report block. This does make the file unnecessarily large when you have a simple report like the one you gave, which doesn't need machinery like Plotly, Vega, etc.

Perhaps we could add a boolean flag to the `report.save` method that allows heavy libraries to be loaded via CDN, which wouldn't support offline viewing but would make the HTML file size much lighter. Another option would be to bundle local NPM assets at runtime and shake off any unused packages, but this would slow down the `save` method significantly.

**Comment by dahanoo** [comment]
Hi Jake,

Understood there's a lot going on under the hood. I think having the choice
to load via CDN or to bundle the assets at runtime would be a good
thing, That'd really help. Especially if things can be cached browser side.

Slowing down the 'save' method may not such a bad thing if devs know it's
going to happen and why. I'm sure some bright minds, yours included, will
find some way around all of this in time.

Still, good to know that the heavy overhead is not directly related to the
data size.

The whole thing is a great idea. especially the offline aspect. Many times
I've needed such a tool!

Danny

**Comment by Buroni** [comment]
Hi Danny, I've created https://github.com/datapane/datapane/issues/25 to track this feature. Closing this issue now as we can continue any further discussion there.
