### ISSUE TITLE
token and graph plotting issues

### ISSUE THREAD

**Issue by pooja-anandani** [datapane/datapane#26]
So, the issue that I am facing is that I am not able to publish the report on the data pane server. 
it is showing the token is invalid but that's not the case I have rechecked it and the token seems fine. 

The second issue is when I am trying to display graphs only the first dp.Plot() method is working and other graphs are shown blank.
I am using google colab with python version 3.6.7

Hope, to get the fix of this issue.

**Comment by mands** [comment]
Hi there @pooja-anandani - thanks for your feedback. So re the token issue, if you are running within jupyter, can you try restarting your kernel and try again? We'll update the docs and error message to reflect this issue this week.

Re your graphs - could you provide some code that demonstrates the issue?

Thanks!

**Comment by pooja-anandani** [comment]
@mands
Re-Token  yes I have done the steps mentioned by you and still, the token thing was not working in google colab. 


Re- graphs : Sure, 

This is the code: 
report=dp.Report(
    dp.Markdown('Corona Virus'),
    dp.Markdown("Active cases country"),
    dp.Plot(active_cases['Active'].plot(kind='barh',xlim=(0,800))),
    dp.Markdown("Active cases over-time"),
    dp.Plot(timeline['Active'].plot(kind='line'))
    )

report.save(path='covid-19-da.html')

Image
![issue1](https://user-images.githubusercontent.com/30249517/94373882-089faf80-0126-11eb-9539-1aeeeabaccfd.PNG)
![solved](https://user-images.githubusercontent.com/30249517/94373884-09d0dc80-0126-11eb-8ad9-85fbd70968ab.PNG)

 1 is the snippet from the HTML generated with the help of datapane and 2nd one is the result that am getting in the notebook

**Comment by lanthias** [comment]
Thanks for this @pooja-anandani ! Could I confirm how you are authenticating on the Colab notebook? I just tried in a new Colab notebook as follows but couldn't reproduce your error:

![image](https://user-images.githubusercontent.com/3541695/94432235-5d771080-018e-11eb-9a5f-db51984ad617.png)

For the matplotlib error above, I believe this is because what the mpl `.plot` method returns and what is shown inline in the notebook are not the same in mpl.

To get the actual figure which is shown inline in the notebook (and which you want to include inside your DP report), I believe you need to get the figure itself by using a method such as `.gcf()` https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.gcf.html

Let me know if this works for you!
