### ISSUE TITLE
Windows dependency on Visual C++

### ISSUE THREAD

**Issue by salamis99** [datapane/datapane#8]
```
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
```

**Comment by giswqs** [comment]
I encountered the same issue with Windows 7. However, the installation on Windows 10 went just fine.

**Comment by mands** [comment]
This may be fixed by installing the Visual C++ Redistributable for Visual Studio 2015, as mentioned at https://arrow.apache.org/docs/python/install.html#using-pip or by using the newly available conda package.

**Comment by mands** [comment]
Closing as fixed by following the extended Windows instructions at https://docs.datapane.com/tutorials/tut-getting-started#windows-tips-and-troubleshooting - most likely requires installing the Visual C++ DLLs package at https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads and by ensuring using a 64-bit version of Python.
