### ISSUE TITLE
Unsupported Feature Error: DataTable

### ISSUE THREAD

**Issue by gfbarbieri** [datapane/datapane#90]
### System Information

- OS: Windows 10
- Python version: 3.7.4 via Anaconda
- Python environment: conda
- Using jupyter: true
- Datapane version: 0.10.2

### Bug / Issue

I was attempting to use the Report module to export a standalone HTML with a table, but received the following error: "UnsupportedFeature: DataTable component not supported when saving locally, please publish to a Datapane Server or use dp.Table Please visit www.github.com/datapane/datapane to raise issue / discuss if error repeats"

The code is simple and mostly from the DataPane examples page, so I reproduced it below.
```python
import datapane as dp
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'A': np.random.normal(-1, 1, 5),
    'B': np.random.normal(1, 2, 5),
})

table = dp.DataTable(df)
report = dp.Report(table)
report.save(path='test.html')
```

**Comment by mands** [comment]
Hi there, apologies for the issue here. We recently added a new `Table` component that can be used locally and updated the interactive `DataTable` component to include some advanced analytical features that require a hosted server component. Unfortunately this means we can no longer support the `DataTable` component when saving locally as a single HTML file -- however we provide a free service for hosting public and private reports on https://datapane.com which supports this.

We're working on updating the documentations and examples currently, however if you want to save tabular reports locally without the server then we recommend using `dp.Table`. HTH!

**Comment by gfbarbieri** [comment]
Thanks for the reply! I noticed that the Table component doesn't appear the same as the DataTable component. Specifically, Table doesn't offer filter/search functionality for the columns. That is, the table is static. Do you think the more dynamic features of DataTable will become available on the Table Component?

As this is a different topic, I will close the issue regardless. Thanks for all the work you do.

**Comment by mands** [comment]
Happy to announce that DataTable is now supported again from version 0.11.6 onwards - HTH!
